accounts/urls.py
from django.urls import path

app_name = 'accounts'

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include('products.urls')),

    # rosetta(i18n)
    path('rosetta/', include('rosetta.urls')),

] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page_view, name='home_page')
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('new product/', views.ProductCreate.as_view(), name='product_create'),
    path('<int:pk>/update product/', views.ProductUpdate.as_view(), name='product_update'),
    path('<int:pk>/delete product/', views.ProductDelete.as_view(), name='product_delete'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

pages/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from multiselectfield import MultiSelectField
from django.urls import reverse


class Stone(models.Model):
    QUALITY_CHOICES = (
        (_('Gemstone'), _('Gemstone')),
        (_('Semiprecious stone'), _('Semiprecious stone'))
    )

    BIRTH_MONTH_STONE_CHOICES = (
        (_('farvardin'), _('farvardin')),
        (_('ordibehesht'), _('ordibehesht')),
        (_('khordad'), _('khordad')),
        (_('tir'), _('tir')),
        (_('mordad'), _('mordad')),
        (_('shahrivar'), _('shahrivar')),
        (_('mehr'), _('mehr')),
        (_('aban'), _('aban')),
        (_('azar'), _('azar')),
        (_('dey'), _('dey')),
        (_('bahman'), _('bahman')),
        (_('esfand'), _('esfand')),
    )

    stone_name = models.CharField(max_length=100, verbose_name=_('stone name'))
    stone_description = models.TextField(verbose_name=_('stone description'))
    stone_properties = models.TextField(verbose_name=_('stone properties'))
    stone_quality = models.CharField(choices=QUALITY_CHOICES, max_length=18, verbose_name=_('stone_quality'))
    birth_month_stone = MultiSelectField(choices=BIRTH_MONTH_STONE_CHOICES, max_choices=5, max_length=50,
                                         verbose_name='birth month stone')

    # birth_month_stone = models.CharField(choices=BIRTH_MONTH_STONE_CHOICES, verbose_name='birth month stone')
    stone_image = models.ImageField(verbose_name=_('stone image'), upload_to='stone_cover/')

    def __str__(self):
        return self.stone_name

    class Meta:
        verbose_name_plural = _('Stones')


class ProductType(models.Model):
    type = models.CharField(verbose_name=_('product type'))

    def __str__(self):
        return self.type

    class Meta:
        verbose_name_plural = _('Product types')


class Product(models.Model):

    MATERIAL_CHOICES = (
        (_('Natural Stone'), _('Natural Stone')),
        (_('Artificial Stone'), _('Artificial Stone')),
    )

    SUITABLE_CHOICES = (
        (_('Men'), _('Men')),
        (_('women'), _('Women')),
        (_('Men and Women'), _('Men and Women')),
    )

    product_name = models.CharField(max_length=200, verbose_name=_('product name'))
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE, verbose_name=_('product type'))
    stone = models.ForeignKey(Stone, on_delete=models.CASCADE, related_name='stones', verbose_name=_('stone'))
    product_material = models.CharField(choices=MATERIAL_CHOICES, max_length=16, verbose_name=_('product material'))
    suitable_for = models.CharField(choices=SUITABLE_CHOICES, max_length=15, verbose_name=_('suitable for'))
    product_color = models.CharField(max_length=20, verbose_name=_('stone color'))
    product_image = models.ImageField(verbose_name=_('product image'), blank=True, upload_to='product_cover/')

    price = models.PositiveIntegerField(verbose_name=_('price'))
    product_inventory = models.PositiveIntegerField(verbose_name=_('Product inventory'))
    product_owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_('product owner'))
    active = models.BooleanField(default=True, verbose_name=_('active status'))

    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('creation date'))
    datetime_modified = models.DateTimeField(auto_now=True, verbose_name=_('Modification date'))

    def __str__(self):
        return f'product: {self.product_name}, {self.product_type}, {self.product_material}'

    class Meta:
        verbose_name_plural = _('Products')

    def get_absolute_url(self):
        return reverse('products:product_detail', args={self.id})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email')

products/forms.py
from django import forms
from .models import Product


class ProductCreationForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'product_name',
            'product_type',
            'stone',
            'product_material',
            'suitable_for',
            'product_color',
            'product_image',
            'price',
            'product_inventory',
            'product_owner',
            'active',
        ]

pages/views.py
from django.shortcuts import render


def home_page_view(request):
    return render(request, 'home_page.html')

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .models import Product
from .forms import ProductCreationForm


class ProductList(generic.ListView):
    context_object_name = 'products'
    template_name = 'product/product_list.html'

    def get_queryset(self):
        return Product.objects.filter(active=True).order_by('-datetime_modified')


class ProductDetail(generic.DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product/product_detail.html'


class ProductCreate(generic.CreateView):
    model = Product
    form_class = ProductCreationForm
    context = 'form'
    template_name = 'product/product_create.html'


class ProductUpdate(generic.UpdateView):
    model = Product
    form_class = ProductCreationForm
    context_object_name = 'form'
    template_name = 'product/product_create.html'


class ProductDelete(generic.DeleteView):
    model = Product
    context_object_name = 'product'
    template_name = 'product/product_delete.html'
    success_url = reverse_lazy('products:product_list')


# def product_list(request):
#     products = Product.objects.filter(active=True).order_by('-datetime_modified')
#
#     context = {'products': products}
#     return render(request, 'product/product_list.html', context)

# def product_detail(request, pk):
#     product = Product.objects.get(pk=pk)
#
#     context = {'product': product}
#     return render(request, 'product/product_detail.html', context)

# def product_create(request):
#     if request.method == 'POST':
#         form = ProductCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('products:product_list')
#
#     else:
#         form = ProductCreationForm()
#
#     context = {'form': form}
#     return render(request, 'product/product_create.html', context)

# def product_update(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#
#     form = ProductCreationForm(request.POST or None, instance=product)
#     if form.is_valid():
#         form.save()
#         return redirect(product.get_absolute_url())
#
#     context = {'form': form}
#     return render(request, 'product/product_create.html', context)

# def product_delete(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         product.delete()
#         return redirect('products:product_list')
#
#     context = {'product': product}
#     return render(request, 'product/product_delete.html', context)

templates/_base.html
{% load i18n %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}{% endblock %}</title>
</head>
<body dir="rtl">

{% if user.is_authenticated %}

    {% trans 'welcome' %} {{ user.username }}
    <a href="{% url 'account_logout' %}">{% trans 'logout' %}</a>

{% else %}

    <a href="{% url  'account_login' %}">{% trans 'login' %}</a>
    <a href="{% url  'account_signup' %}">{% trans 'signup' %}</a>

{% endif %}

<p>
    <a href="{% url 'pages:home_page' %}">{% trans 'Home' %}</a>
    <a href="{% url 'products:product_list' %}">{% trans 'prodrct lists' %}</a>
</p>


{% block content %}
{% endblock %}
</body>
</html>

templates/home_page.html
{% extends '_base.html' %}
{% load i18n %}

{% block page_title %}
     StoneHomeGallery
{% endblock %}

{% block content %}
    <p><b>{% trans 'Home Page' %}</b></p>
{% endblock %}

templates/product/product_create.html
{% extends '_base.html' %}
{% load i18n %}

{% block page_title %}
     StoneHomeGallery/{% trans 'create new product' %}
{% endblock %}

{% block content %}
    <h4>{% trans 'Please add your product details' %}:</h4>
    <form action="" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans 'add product ' %}</button>
    </form>

{% endblock %}

templates/product/product_delete.html
{% extends '_base.html' %}
{% load i18n %}

{% block page_title %}
    StoneHomeGallery/{% trans 'delete' %}/{{ product.product_name }}
{% endblock %}

{% block content %}
    <h4>{% trans 'Are you sure to remove the ' %} {{ product.product_name }} ?</h4>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="{% trans 'Yes' %}">
        <a href="{{product.get_absolute_url}}" type="btn">{% trans 'No' %}</a>
    </form>

{% endblock %}

templates/product/product_detail.html
{% extends '_base.html' %}
{% load i18n %}

{% block page_title %}
    StoneHomeGallery/{{ product.product_name }}
{% endblock %}

{% block content %}
    <h4>{{ product.product_name }}</h4>
    <p>
         <a href="{% url 'products:product_update' product.id %}">{% trans 'Edit' %}</a>
        <a href="{% url 'products:product_delete' product.id %}">{% trans 'delete' %}</a>
    </p>

    <p>{% trans 'product type' %}: {{ product.product_type.type }}</p>
    <p>{% trans 'stone name ' %}: {{ product.stone.stone_name }}</p>
    <p>{% trans 'stone quality' %}: {{ product.stone.stone_quality }}</p>

    <P>
        {% trans 'birth month stone' %}:
        {% for month in product.stone.birth_month_stone %}
            <b>{{ month }}،</b>
        {% endfor %}
    </P>

    <p>{% trans 'product material' %}: {{ product.product_material }}</p>
    <p>{% trans 'suitable for' %}: {{ product.suitable_for }}</p>
    <p>{% trans 'product color' %}: {{ product.product_color }}</p>
    <p>{% trans 'product inventory' %}: {{ product.product_inventory }} {% trans 'number' %}</p>
    <p>{% trans 'price' %}: {{ product.price }}</p>
    <p>{% trans 'stone description' %}: {{ product.stone.stone_description|linebreaksbr }}</p>
{% endblock %}

templates/product/product_list.html
{% extends '_base.html' %}
{% load i18n %}

{% block page_title %}
     StoneHomeGallery/{% trans 'product lists' %}
{% endblock %}

{% block content %}
    <a href="{% url 'products:product_create' %}">{% trans 'create new product' %}</a>
    {% for product in products %}
        <h4>{{ product.product_name }}</h4>
        <p>{% trans 'suitable for' %}: {{ product.suitable_for }}</p>
        <a href="{{ product.get_absolute_url }}">{% trans 'More' %}</a>
        <hr>
    {% endfor %}

{% endblock %}